%\VignetteIndexEntry{targetSeqView Vignette}
%\VignetteKeywords{alignment}
%\VignettePackage{targetSeqView}
\documentclass{article}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage[numbers]{natbib}
\usepackage{color}
\usepackage[margin=1in]{geometry}
\usepackage{setspace}
\bibliographystyle{plain}

\newcommand{\scscst}{\scriptscriptstyle}
\newcommand{\scst}{\scriptstyle}
\newcommand{\Rpackage}[1]{\textit{#1}}
\newcommand{\Rfunction}[1]{\texttt{#1}}
\newcommand{\Robject}[1]{\texttt{#1}}
\newcommand{\Rclass}[1]{\texttt{#1}}
\newcommand{\R}{\textsf{R}}
\newcommand{\targetSeqView}{\Rpackage{targetSeqView}}
\newcommand{\comm}[1]{{\color{blue}{\small #1}}}


\title{viewing and scoring alignments for structural rearrangements}
\author{Eitan Halper-Stromberg}

\begin{document}




\maketitle

<<<setup, echo=FALSE>>=
    library(targetSeqView)
    options(width=70)
@

\begin{abstract}
This package is designed to evaluate structural rearrangment calls from a candidate list, the output for tools such as
HYDRA \cite{Quinlan2010},GASV \cite{Sindi2009},VariationHunter \cite{Hormozdiari2010}, etc. The user should have a text file with one row per candidate structural rearrangment. For each
candidate rearrangement, read-pairs from the two loci will be read in from a bam file and realigned three different ways.
One of these realignments supports the structural variant, with readpairs realigned to a sequence representing the rearranged
sequence (the sequence of the two loci concatenated together). The other two realignments support no structural rearrangement,
with readpairs realigned to the two sequences representing contiguous fragments of the reference genome taken from each of the two loci.
\end{abstract}

<<pkgs,eval=TRUE>>=

@

\section{Quick Start Example}
We start with a text file containing 20 candidate deletion junctions and the bam file containing our read alignments from a whole
genome sequencing experiment (for the purposes of this vignette the bam file contains only reads aligning within the regions that we will
interrogate). The text file contains the loci allegedely involved in each deletion, one deletion per row. For each row we will load
reads aligning to the two loci involved in the alleged deletion from our bam file, realign these reads, and calculate our
likelihood score.

<<instantiateDel,eval=TRUE>>=
path <- system.file("extdata", package="targetSeqView")

## This method utilizes the foreach package for parallelization, set nodes to however many cpus are
## available.
nodes=1
registerDoMC(nodes)

## create an instance of the candidates class
candidateDels<-new('candidates')
## set the path where bam files are located (if not in the currect working directory)
bamFilePath(candidateDels)<-path
## set the name of the text file containing candidate SVs (full path if not in the working directory)
candidatesFileName(candidateDels)<-file.path(path,'wholeGenomeDeletionCandidates.txt')
## set the build of the (human) genome
build(candidateDels) <- 'hg19'
## set the read length
readLength(candidateDels) <- 101
## set the mismatch rate for each position along the read length
mmRate(candidateDels) <- precomputedWholeGenome101bpMMRate()
## set the indel rate for reach position along the read length
indelRate(candidateDels) <- precomputedWholeGenome101bpIndelRate()
@

note: mismatch and indel rates may be calculated based upon reads from a bam file containing
normal alignments, the bamFile argument should contain the full path with the bam name if the
bam is not in the current directory. The following 3 lines are unevaluated in this vignette
<<computeErrorRates,eval=FALSE>>=
 normalBam <- 'Path/To/Normal/bamfile.bam'
errorRates<-getErrorRate(normalBam)
mmRate(candidateDels) <- errorRates[['mmRate']]
indelRate(candidateDels) <- errorRates[['indelRate']]
@

We first obtain likelihood scores for candidates without performing full smith-waterman
realignment on all reads for all 3 alignement configurations. We instead use alignment
information in the cigar strings and md tags in our bam file to obtain mismatches and indels
for the alignments supporting SVs. In addition, We forgo, for the moment, returning a
data.frame formatted for our plot function. This should take a few (1-5) seconds per candidate
<<quickscore,eval=TRUE>>=
candidateDels<- quickScore(candidateDels,verbose=TRUE)
## view values returned
print(candidateDels@quickScore)
### In this case we have validation data for these candidates
indexOfvalidated <-1:10
validated<-candidateDels@quickScore[indexOfvalidated]

failedvalidation<-candidateDels@quickScore[-indexOfvalidated]
@
\subsection*{Figure \ref{fig:plotquickscore}: The distribution of those that validated and those that did not}

<<plotquickscore,fig=TRUE,include=FALSE>>=
boxplot(list(validated=validated,failed=failedvalidation,
    all=candidateDels@quickScore),ylab='log likelihood score')
@


\begin{figure}[t]
  \begin{center}
  \includegraphics[width=\textwidth]{targetSeqView-plotquickscore}
  \caption{\label{fig:plotquickscore} Distribution of 20 candidate deletions taken from a whole-genome sequencing dataset, broken down
by validation status}
  \end{center}
\end{figure}



\section{Scoring and Viewing}
In this section we will view read alignments at the junctions of 3 candidate structural variants. We will use a sequencing dataset
taken from a target-capture exerpiment. As with the last section, we start with a text file containing the candidate structural
variants (in this case 1 inversion and 2 chromosomal translocations) and a bam file containing read alignments.
<<instantiateSV,eval=TRUE>>=
## create an instance of the candidates class
candidateSVs<-new('candidates')
bamFilePath(candidateSVs) <- path
candidatesFileName(candidateSVs) <- file.path(path,'targetCaptureSVs.txt')
build(candidateSVs) <- 'hg19'
readLength(candidateSVs) <- 100
mmRate(candidateSVs) <- precomputedTargetCapture100bpMMRate()
indelRate(candidateSVs) <- precomputedTargetCapture100bpIndelRate()

## fullScoreAndview will perform full smith-waterman realignment for all reads in the 3
## configurations. In addition, if the input text file contains a SplitsSample column,
## the function will look for split-reads within the bam file specified by the column 'SplitsSample'
candidateSVs<-fullScoreAndView(candidateSVs,verbose=TRUE,findSplitReads=TRUE)
@


The scores for these 3 events:
<<printscore>>=
print(candidateSVs@fullScore)
@

\subsection*{Figure \ref{fig:negative}: A chromosomal translocation that failed to validate}
PCR validation informs us that the first event is negative and the other two are positive.
Let's View the negative (the flipLeftandRight argument is just a style preference, in this
case putting the chr14 junction on the left and the chr15 junction on the right)
<<plot1,fig=FALSE,eval=TRUE>>=
plotSV(candidateSVs,indices=1,flipLeftandRight=TRUE,pdfname='fig1.pdf')
@

\begin{figure}[t]
\centering
\includegraphics[width=1\textwidth]{fig1.pdf}
\caption{\label{fig:negative}A negative (i.e not real) chromosomal translocation. The top plot shows read-pair alignments
supporting the SV and the bottom plots show read-pair alignments supporting contiguous sequences.}

\end{figure}



\subsection*{Figure \ref{fig:positive1}: A validated inversion}
Let's view the first positive. Read-pair alignments supporting the SV look good, read-pair
alignments supporting contiguous fragments do not look good because in both contiguous fragment
alignment pictures, one read from each pair has many mismatches/indels
Figure \ref{fig:positive1})
<<plot2,fig=FALSE,eval=TRUE>>=
plotSV(candidateSVs,indices=2,pdfname='fig2.pdf')
@


\begin{figure}[t]
\centering
\includegraphics[width=1\textwidth]{fig2.pdf}
\caption{\label{fig:positive1}A positive (i.e real) inversion. The top plot shows read-pair alignments
supporting the SV and the bottom plots show read-pair alignments supporting contiguous sequences.}

\end{figure}



\subsection*{Figure \ref{fig:positive2}: A validated chromosomal translocation}
Lets view the second positive. Read-pair alignments supporting the SV look good, albeit for a
different reason than the first positive. In this picture we have some reads aligning well to the
chr14 side and their partners aligning across the junction of the SV (i.e split-reads). The
split-reads align well to both sides. There are a few mismatches right at the junction for these
split reads but otherwise they match the reference. The contiguous fragment alignments do not look
good, as we would expect. Again, the flipLeftandRight option is a style preference, putting the
chr14 junction on the left and the chr18 junction on the right.
Figure \ref{fig:positive2}
<<plot3,fig=FALSE,eval=TRUE>>=
plotSV(candidateSVs,indices=3,flipLeftandRight=TRUE,pdfname='fig3.pdf',width=10)
@



\begin{figure}[t]
\centering
\includegraphics[width=1\textwidth]{fig3.pdf}
\caption{\label{fig:positive2} A positive (i.e real) chromosomal translocation. The top plot shows read-pair alignments
supporting the SV and the bottom plots show read-pair alignments supporting contiguous sequences.}

\end{figure}



<<sessionInfo,results=tex>>=
toLatex(sessionInfo())
@


%%\section*{References}
\bibliography{refs}

\end{document}
